# Generated by Django 3.2.16 on 2023-01-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230126_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(default='senior', max_length=15),
            preserve_default=False,
        ),
    ]
